scam = [
    'Gods and Titans Mint Pass Original',
    'Valorant Mint Pass Official',
    'Walking Mushroom Mint Box Limited',
    'KRDH Official',
    'Crypto Diverse Items',
    'YUGA: Gucci Merch PASS',
    'Overwatch SZN1 Mint Pass Limited',
    'FCKIT',
    '$1000 USDC - 0',
    'LIDO NFT TICKETS - 1',
    'Visit ethena-2l.com to claim rewards',
    'VWIN - 872448',
    'Super Boys Orignal - 1',
    'TONCrypto.io',
    'Warning - 31093',
    'SEB',
    'ZIKTOKEN.COM-SWAP AND GET 100 ZEC',
    '10 000 USD FOR FREE - 10034870321424364224204695929735558941153547521495712359208821587756539969537',
    'BEP-20 TOKEN',
    '$1000 REWARDS - 0',
    '$1000 Rewards - 0',
    'BSC',
    'OPTOPUS',
    'TheSandBox.PRO',
    '1 stETH - 0',
    '$ELO Coin Launch Party - 0',
    'FOMO',
    '!1 0PENSEA V0UCHER - 0',
    'BSC-USD',
    'MATIC BONUS - 5838',
    'WGC',
    'FOMEDOG',
    '0xab57aef3601cad382aa499a6ae2018a69aad9cf0',
    'cronosclassic.com',
    '$!$ 30,000 BONE - 0',
    'ApeCoin NFT - 434',
    '0xe592427a0aece92de3edee1f18e0157c05861564',
    'LIDO WHITELIST - 1196',
    '$ Visit blasdot.com to claim rewards!',
    '0xf3822314b333cbd7a36753b77589afbe095df1ba',
    'Claim on: sandbox.droptokens.net/?claim',
    'UnisMeta 1671392971464 - 153',
    'AI-A',
    '$USDT СLАIМ▷lootusdt.com',
    'BOLG',
    'KURO',
    '0Army.io',
    'Magma CO Pass - 28',
    'OPT',
    '1099$ USDC - 83215',
    'RTFKT - MNLTH CVD X - 199',
    'ABFIN',
    'KURO  [www.kuroro.gg]',
    '#Synthetix.cc (sUSD)',
    '0x794a61358d6845594f94dc1db02a252b5b4814ad',
    'Life Goes On 846 Meta - 273',
    'Airdrop on: brettbased.com',
    'LOOKSDROP.COM',
    'SavageNation LW Tournament Pass Originals - 24',
    'Star Fighter Club QX - 31',
    'Uniswap Summer Event - 176',
    'AVALANCE NFT TICKETS - 9335',
    'MNEB',
    'CRONOSCLASSIC.COM',
    'BAYC Airdrop - 12',
    'Zepe.io',
    'FCKIT',
    '2500 USDT by ETHERSCAN x METAWIN - 0',
    'XEN',
    '5000 USDC - 0',
    'TRC20CUPON.COM GET 2000usdt NOW',
    'pepewife',
    'EVER',
    'BlurredApeYachtClub - 0',
    'APE NFT TICKETS - 8432',
    'StakeEther.co',
    '! !$100,000 BONE - 0',
    'DarkoZoo - 9101',
    'LIDO WHITELIST - 1',
    'Get stETH airdrop ( https://droppradar.space )',
    'Visit https://jbonus.site to claim reward',
    '995$ Visit USDTReward.com to claim',
    '0x59C1A84420027e17ddb3E37e5489dc20504e9435',
    '0x3f0B8B206A7FBdB3ecFc08c9407CA83F5aB1Ce59',
    'Gods and Titans Mint Pass Original - 103',
    'Nested Box BJ Club - 36',
    'YUGA: Gucci Merch PASS - 35',
    'wSNX',
    'wHEX',
    'Claim on: rewards.aerodrome-network.com',
    '2,000 USDT Reward - 0',
    'Collect on: swap-based.com',
    '$ sUSD',
    'FUNGI',
    '5000 USDC Voucher - 0',
    'Visit sufek.com and claim special rewards',
    'Milady NFT Gift - 1',
    'Walking Mushroom Mint Box Limited - 509',
    '0xd9c242f6Ca08Fe45C58CA9E9A8558CFE7497E7c2',
    'Kodao-G Membership - 28',
    'BaseWif',
    '$2000 USDT Airdrop - 1',
    'PPBox.io',
    'Visit stETH official website:  steth-voucher.site',
    'MGRT',
    'DOG',
    'AIR',
    '$$30,000 BONE - 0',
    'DBT',
    'sUSD [Synthetix.cc]',
    'ULand Genesis Item - 1',
    'Claim at: claim.fungi-airdrop.com',
    'Acces Liquid-ether.com to claim rewards',
    '$1000 SPEND REWARDS - 0',
    'lrETH',
    'boom',
    'Boom',
    'Overwatch SZN1 Mint Pass Limited - 288',
    'Claim on: mogcoins.net/?claim',
    'Staked Bitrock (www.bitrock.app)',
    'https://wincoin.win/',
    'Visit Lido-event.site to join LIDO Giveaway!',
    'Wifs',
    'The QPT Originals - 336',
    'vanity-address.io',
    '5 ETH Voucher by Base - 0',
    'wRDNT',
    'PEPE WIFCOIN',
    '1 WETH - 560631',
    '$ Free Claim and Play',
    '4,651$ SHIB - 0',
    'BNBW',
    'BEP-20',
    'BENTO',
    '1000$ Reward - 0',
    '0xB8c8A93168Bb610428c85EB9c9e253768C36e67D',
    'The Mutants Return Land Pass Officials - 1',
    'Claim USDC/WETH at https://USDCpool.site',
    'Crypto Diverse Items - 258',
    'dYdX Exchange Event - 202',
    'Claim on: brettbased.com',
    'BSCTOKEN',
    '! !$100,000 SHIB #1 - 0',
    'TONCRYPTO.IO',
    'BalancerV2.com',
    'BAYC Airdrop - 13',
    'KRDH Official - 257',
    'Acces stETHERS.COM to claim rewards',
    '$$$AIRDROP 0PENSEA - 45975694115932666297700772423167124246419737974611922237769215783254357966850',
    'BS69',
    'Acces zerolends.com to claim reward',
    'The Sougen Genesis Pass - 1',
    'XEC',
    'VERA',
    '$USDT СLАlМ▷airUSDT.net',
    'StarBored - 8014',
    'Claim USDC at https://cusdcs.eth.li',
    'DogX.AI NFT',
    'Anatomic WCE Apes - 532',
    'Wiz GGY Box - 131',
    'BASEMEMES',
    'MKS',
    'PLEB GME',
    'MOEW',
    'A-ZKF [www.zkfair.events]',
    'Visit blast2l.com to claim rewards',
    'APE NFT TICKETS - 1781',
    'SHIBPOOL.COM - 1',
    'PEPEX314',
    'Valorant Mint Pass Official - 8',
    'STEIN-CHESS.COM | AirDrop - You are invited',
    'BLUR EVENT - 2009',
    'Otherdeed Coda Key - 2',
    'ACX   [via www.across.events]',
    'Claim by link: https://claim.eigen.click',
    'DVP',
    'Visit 3eth.co to claim reward.',
    'Visit [5000usdc.org] to claim Airdrop',
    'BTN',
    'Visit rocketpool.win to claim 10 rETH.',
    'ACCESS [ETHNA.CC] TO CLAIM YOUR TOKENS',
    '$ L-ZERO.COM | AirDrop',
    '$ Check: goldblast.io Your Gold AirDrop',
    'Visit Tether.re to claim 10000 Rewards',
    'Visit Wbtc.win to claim reward',
    'Visit Rocketpool.win to claim Reward.',
    'Visit Shiba.pm to claim Airdrop.',
    'FRANK',
    'Boe',
    'BOOMER',
    'BORD',
    'PEEZY',
    'USA',
    'WAZ',
    'DOOMER',
    'Nippy',
    'PEPEALB',
    'Dragon Balls Token',
    'eCash',
    'AI Avail',
    'XEN Crypto',
    'BOOM',
    'Milkyswap.io',
    'My Get Rich Token',
    'ShibaDrop.io',
    'TheVera.io',
    'AirStack.net',
    'TheEver.io',
    'BSCTOKEN.IO',
    'Minereum BSC',
    'BestAir.io',
    'BNBW.IO',
    'ABFIN.org',
    '+ $50 000 (BONUS-ETH.NET)',
    'Meataversity of Steak-umm Merch',
    'DarkoZoo',
    'Pop NFT Worlds Avatar Mint Pass Collection',
    '3D Apes IKM Planet',
    'UnisMeta 1671392971464',
    '1 WETH',
    'Wiz GGY Box',
    'ApeCoin NFT',
    'RTFKT X NIKE MONOLITH YZ Special Pass Originals',
    'MyLand Metaverse Original',
    'POLYGON COCKPUNCH XJB PASS Genesis',
    'DEZUKI CA NFT',
    'Andromeda Access Pass',
    'Astronomia Meta 1669677708106',
    'The Saudi Meta Airdrop',
    'Anatomic WCE Apes',
    'RTFKT - MNLTH CVD X',
    'CyberSamurai MG Ticket',
    'The QPT Originals',
    'Life Goes On 846 Meta',
    '2000 STG NFT Voucher',
    'ULand Genesis Item',
    '1,000 USDT',
    'Warning',
    'StarBored',
    'Wiz QBM Box',
    '🎁 Bonus at 5eth.us',
    'Reward at 2000usdc.net 🎁',
    'Milady NFT Gift',
    'Virtual Keungz Kubz Original Pass',
    '! !$100,000 BONE',
    '$2000 USDT Rewards',
    'SavageNation LW Tournament Pass Originals',
    '1000$ Reward',
    '10BNB at 10bnb.us 🎁',
    '1,000 USDT Reward',
    '!1 0PENSEA V0UCHER',
    'USDT Airdrop',
    'Kodao-G Membership',
    '$!$ 30,000 BONE',
    'Waifumon.com World Record Drop',
    'Uni NFT Event',
    '$1000 Rewards',
    '700M SHIB',
    'OpenSea Collections',
    'The Chainzoku Collection',
    'Magma Official D',
    '$5000 USDT Airdrop🎁',
    '200M SHIB',
    'ApyMatic.org',
    'Otherdeed Coda Key',
    '1 stETH',
    '$1000 REWARDS',
    "'",
    '$1000 USDC Voucher🎁',
    'MATIC BONUS',
    'ARB VOUCHER',
    'BitCase FREESPIN',
    '5000 USDC',
    'SHIBPOOL.COM',
    'POLKADOT EVENT',
    '$3000 USDT Airdrop🎁',
    '$1000 USDC',
    'NutsDao Avatars  Items',
    'ApyMatic.net',
    '$2000 USDC',
    'Uniswap V3: Rewards NFT',
    '$5000 USDC',
    'BullvBear Access Keys',
    '! ! ! $100,000 BONE',
    'MechDog vs MechMonkey New Pack',
    'The Sougen Genesis Pass',
    'APE NFT TICKETS',
    'TulipArt Airdrop for Otherdeed for Otherside',
    'Ledger Stax: Giveaway',
    'The Dookey Dash Pass NFT',
    'AVALANCE NFT TICKETS',
    '$MEME Voucher',
    'Claim Wormhole Airdrop: wormhole-airdrop.org',
    'Polygon Plus Event',
    'Pudgy Penguin 2857',
    'Uniswap NFT Event',
    '15,000$ SHIB',
    '$2000 USDC Voucher🎁',
    '1,000 UNI by Uniswap',
    'dYdX Event',
    '125M SHIB NFT Voucher',
    'BAYC Airdrop',
    '500M SHIB',
    'Star Fighter Club QX',
    '\xad',
    '$ 5000 at web3shiba.us 🎁',
    'Uniswap Summer Event',
    'BLUR EVENT',
    '2500 USDT by ETHERSCAN x METAWIN',
    '$$$AIRDROP 0PENSEA',
    'Nested Box BJ Club',
    '5000 BUSD',
    'Stoned APE Pass J',
    'Lions Not Sheep  Limited',
    'receivegift.org',
    '5000 USDC Voucher',
    'LIDO WHITELIST',
    '$2000 USDT Airdrop',
    '$1000 USDT Airdrop',
    'KodaPendant Extra Pass Genesis',
    'Play2Earn - PM1',
    '$ELO Coin Launch Party',
    'BlurredApeYachtClub',
    '5 ETH by Base',
    'REVOLUTION',
    'OPTIMISM NFT TICKETS',
    'Magma CO Pass',
    '2000 USDC Voucher',
    '! !$100,000 SHIB #1',
    '! !100 BNB',
    'LIDO NFT TICKETS',
    'Bitinauts Pass',
    '10 000 USD FOR FREE',
    '1',
    'TulipArt Airdrop',
    'SHIB POOL VOUCHER',
    '1,000 USDT Voucher',
    'Airdrop at 3eth.top 🎁',
    '$100,000,000 SHIB',
    'The MG Super Land Pass Limited',
    'Nested Boxes TB Community',
    '500M',
    '$1000 SPEND REWARDS',
    'VWIN',
    '5.00 ETH by Base',
    '5 ETH Voucher by Base',
    '1099$ USDC',
    'ARBITDROP.INFO COUPON',
    '🎁10K$ gift at [bit.ly/tpepe]',
    '125M SHIB',
    'Adventurous',
    'Reward at 5000usdc.cc 🎁',
    '5,000 BUSD',
    'UNI EVENT',
    "''",
    'The Mutants Return Land Pass Officials',
    'CryptoTab Official Drop No.2',
    '$100,000 BONE',
    '# Sponsored',
    'Super Boys Orignal',
    '2,000 USDT Reward',
    'Hero Galaxy SM Club',
    '$3000 USDT Airdrop',
    'V4A9QR',
    '1000 USDC',
    'dYdX Exchange Event',
    'Airdrop at 5eth.net 🎁',
    '$$30,000 BONE',
    '4,651$ SHIB',
    'NFT Voucher Giveaway!',
    '5000 BUSD Voucher',
    '#LRETH.COM',
    'Dinoverse Pass',
    'APECOIN',
    'SEBASTIEN BORGET Token',
    'uniswap.cab',
    '!SNXPool.com',
    'Coinmap AI',
    'AAVEPool.com',
    '# RADIANTCAPITAL.US',
    'Hwape',
    'grilape',
    'Crypto Animals 2',
    '1000 UNI',
    'Reward at 5000usdc.xyz 🎁',
    'Steakumm Diploma',
    'UNISWAP EVENT',
    '$2000 REWARDS',
    'Airdrop at usdtredeem.com',
    'Airdrop at 3eth.cc 🎁',
    '3K$ at getusd.us 🎁',
    '! $5,000 USDC',
    '$1000 GET',
    '50M $SHIB Voucher',
    '1.2827 cbETH',
    '$5000 USDC Voucher',
    '$5000 BUSD Voucher',
    '20,000 USDT Reward',
    '700 LDO AIRDROP',
    '1,000 UNI',
    '!! Kuroro.io',
    'BITMAN TOKEN',
    'Wild Goat Coin',
    '#HEXPool.net',
    '+$50 000 (BONUS-ETH.NET) 🎁',
    'Mutant Grape Wine Club',
    'BaseTurds',
    'DeBox Soulbound Token',
    'WIFS',
    'Base Lord',
    'Boe',
    'Doomer',
    'FOMEDOG',
    'BOLG',
    'Boomer',
    'Farmer Frank',
    'PLEB GME',
    'Degen$mferDinoKeycatFungiRoostDoginmeNyanHigherPatCjElonrwaBenjiCapooBunnyBasemoon',
    'Oomer',
    'MikeAI',
    'Cat On Catnip',
    'Fungi',
    'BASED USA',
    'The Doge NFT',
    'BaseStation 69',
    'PEPEALB',
    'pepewife',
    'PEPEX314',
    'donotfomoew',
    'Young Peezy AKA Pepe',
    'Father Of Meme',
    'BaseWif'
]
